<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-11 16:46
=======
# Generated by Django 5.0.1 on 2024-01-18 10:57
>>>>>>> c5a3a59 (Initialisation et sélection des informations)

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.TextField()),
                ("species", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> c5a3a59 (Initialisation et sélection des informations)
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("phoneNumber", models.IntegerField()),
            ],
        ),
    ]
