# Generated by Django 5.0.1 on 2024-01-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='annotated',
            field=models.BooleanField(default=False, verbose_name='annotated'),
        ),
        migrations.AddField(
            model_name='protein',
            name='annotated',
            field=models.BooleanField(default=False, verbose_name='annotated'),
        ),
    ]
