# Generated by Django 5.0.1 on 2024-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_genome_annotated_protein_annotated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protein',
            new_name='GeneProtein',
        ),
    ]
