# Generated by Django 4.2.7 on 2024-01-28 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_annotationgenome_annotated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneprotein',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 1, 28, 14, 20, 54, 210129, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
