# Generated by Django 5.0.1 on 2024-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_protein_geneprotein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
