# Generated by Django 4.2.7 on 2024-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_geneprotein_upload_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationgenome',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
        migrations.AddField(
            model_name='annotationprotein',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
