# Generated by Django 5.0.1 on 2024-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_annotationgenome_is_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationgenome',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='annotationprotein',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='geneprotein',
            name='annotated',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='annotated',
        ),
        migrations.AddField(
            model_name='annotationgenome',
            name='is_annotated',
            field=models.BooleanField(default=False, verbose_name='annotated'),
        ),
        migrations.AddField(
            model_name='annotationprotein',
            name='is_annotated',
            field=models.BooleanField(default=False, verbose_name='annotated'),
        ),
        migrations.AddField(
            model_name='geneprotein',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
        migrations.AddField(
            model_name='genome',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
