# Generated by Django 4.2.7 on 2024-01-26 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_genome_annotated_annotationgenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationgenome',
            name='annotator',
            field=models.ForeignKey(default='unknown_annotator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
