# Generated by Django 4.2.7 on 2024-01-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_annotationgenome_annotator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genome',
            old_name='annonations',
            new_name='annotations',
        ),
    ]
