# Generated by Django 5.0.1 on 2024-02-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('website', '0008_alter_annotationprotein_geneprotein_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnotationValidation',
            new_name='AnnotationStatus',
        ),
    ]
