# Generated by Django 5.0.1 on 2024-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('website', '0011_alter_profile_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnotationStatu',
            new_name='AnnotationStatus',
        ),
        migrations.AlterField(
            model_name='genome',
            name='chromosome',
            field=models.CharField(max_length=255),
        ),
    ]
