# Generated by Django 5.0.1 on 2024-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_annotationstatu_annotationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationstatus',
            name='status',
            field=models.CharField(choices=[('validated', 'validated'), ('pending', 'pending'), ('refused', 'refused')], default='', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
    ]
