# Generated by Django 5.0.1 on 2024-02-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_annotationstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationstatus',
            options={'verbose_name_plural': 'Annotation status'},
        ),
    ]
